### ISSUE TITLE
State pattern class constructor

### ISSUE THREAD

**Issue by BastyZ** [BastyZ/RTreesImplementations#20]
Esta clase decide que heurística se usará al insertar nodos, la idea es que use `double dispatch` para solucionar de manera elegante el problema de elección, los objetos que representan cada heurística solo tendrán una función que recibe un nodo, y le indica que función usar según la heurística que le corresponda.

**Comment by BastyZ** [comment]
Los nodos tendrán el estado de la forma que se indique en #21 sobre la estructura de los nodos

**Comment by AnnBenavides** [comment]
Interfaz (StateInterface) y una subclase (LinearSplit) creadas, por que no recuerdo que otro método ibamos a usar xD
Todas con una sola función por ahora: **+name()::String** que entrega el nombre del método overflow que le corresponde

**Comment by BastyZ** [comment]
@AnnBenavides Ibamos a usar Greene's Split, porque se parecia
