### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by BastyZ** [BastyZ/RTreesImplementations#22]
Esta función retorna un `ArrayList` con los rectangulos que se intersectan #15 con el parametro de busqueda, se parte desde la raiz, y si un nodo interno intersecta el parametro, se agregan todos sus hijos a la búsqueda; si se trata de una hoja, entonces esta se agrega al `ArrayList` con el resultado que retorna la función.

Recibe: `Rectangle aRectangle`
Retorna: `ArrayList<Rectangle> found`

**Comment by AnnBenavides** [comment]
requiere de Rectangle #15 
**+intersects(Rectangle r) :: boolean**

se agregaron funciones privadas para quitar verbouse, #23 related
**-getChildAddress(int index) :: Long** : entregandoles el index busca en _children_ la dirección en memoria de dicho hijo
**-getChild(int index) :: Node** : tomando el index de _children_ correspondiente a cierto hijo, carga el objeto y lo retorna
