### ISSUE TITLE
Insert function for Node Class

### ISSUE THREAD

**Issue by AnnBenavides** [BastyZ/RTreesImplementations#24]
Su firma seria
**insert ( Rectangle r, ISplit overflow) :: long** : con _r_ el rectángulo a insertar ( #6 ) y _overflow_ el método que se usará para manejar los casos de overflow ( #20  )

**Retorna** una dirección de memoria, en caso de overflow, de lo contrario retorna _null_ . La dirección retornada corresponde al nuevo hijo creado para guardarlo posteriormente.

- [x] Si el nodo es una hoja se agrega _r_ a _rectangles_ y un _null_ a _children_
Si estamos en un nodo interno, hay que decidir por donde bajar para esto:
- [x]  Creamos una lista de rectángulos candidatos
  -  Inicializamos una variable auxiliar para guardar el área [_area_] en la que aumenta el mejor rectángulo probado, y otra variable de index
  -  Iteramos por cada elemento de _rectangles_ y calculamos su MBR ( #12 ) y calculamos su diferencia en area con _area_ para comparar [_deltaMBR_]
    - caso base : se agrega a candidatos
    - caso en que _deltaMBR_ sea igual a _area_ : se agrega a candidatos
    - caso en que _deltaMBR_ sea menor a _area_ : se vacia la lista de candidatos, se agrega el rectangulo actual y _area_ se actualiza a _deltaMBR_
- [x] Si tenemos un solo candidato, se deja la lista como está, sino:
  - inicializamos la variable auxiliar _area_ con el mismo fin de los pasos anteriores
  - creamos una segunda lista de candidatos
  - iteramos sobre la primera lista de candidatos,:
    - caso base :  siempre el area es menor
    - caso area del candidato es igual a _area_ :  lo agrego a la nueva lista de candidatos
    - caso area del candidato es menor a _area_: vació la nueva lista de candidatos, inserto el actual y seteo _area_ con el actual.
  - igualamos la primera lista de candidatos a la segunda (quedando con un solo candidato)
- [x] insertamos el en el rectangulo elegido
  - cargamos el hijo del rectangulo elegido 
  - insertamos _r_ con la estretegia _overflow_ en dicho hijo (**paso recursivo**) obteniendo _of_ (dirección de memoria del nuevo hijo en caso de overflow o null sino)
  - recalculamos MBR del nodo actual
  - si hubo overflow agregar al nuevo hijo y su rectangulo en _rectangles_ y _children_
- [x] si no huo overflow se guarda el nodo y se **retorna** _null_
- [x] si hay overflow hay que hacer split
  - Creamos dos listas de direcciones y rectanglulos para los futuros dos nodos
  - Escogemos e insertamos los rectangulos iniciales de las listas para los nuevos hijos según el método de overflow elegido ( Lineal #25  o Greene #26 Split) en listas distintas
  - Rellenamos las listas de la siguiente forma:
    - Tomamos un rectángulo, al azar, de los restantes.
    - Se agrega al nodo cuyo MBR crezca menos
    - Se recalcula el MBR de dicho nodo
    - **Importante** ambos nodos terminan con al menos _m_ rectángulos
- [x] si el nodo **es raíz**
  - Crea dos hijos, por lo que _rectangles_ y _children_ sólo los contendrá a ellos
  - Se guardan los tres nodos ( #13 )
  - Retornar null
- [x] Finalmente acualizo el nodo actual:
  - Reemplazo los daos por las del primer split
  - Creo un nuevo nodo hermano, le asigno una dirección y le doy los datos del segundo split
  - Se guadan los dos nodos, actual y hermano, y se retorna la dirección del segundo.

**Comment by AnnBenavides** [comment]
se agregó la fx privada relevante para #23 
**-getRectangle(int index) :: Rectangle** que entrega el objeto en la posición _index_ de _rectangles_

**-resetAndAdd(int i) :: ArrayList<Integer>** : crea un arrayList vacio y le agrega el elemento _i_ quedando como único elemento.

**Comment by AnnBenavides** [comment]
para el segundo punto se necesita en Rectangle las funciones #14 #6 
**+calculateSimMBR(Rectangle r, Rectangle temp) :: float** : que tome el MBR de agregar _r_ en _temp_ y entregue su área
**+area() :: float** que calcula el área del rectángulo

**Comment by AnnBenavides** [comment]
agregue nueva funcion privada
**-addChild(Rectangle r, Long addr) :: void** : agrega _r_ a _rectangles_ y _addr_ a _children_
#21 related

**Comment by BastyZ** [comment]
en rectangles deltaMBR es __deltaArea(*Rectangle* r1, *Rectangle* r2):: double__
