### ISSUE TITLE
Greene's Split for Node Class

### ISSUE THREAD

**Issue by AnnBenavides** [BastyZ/RTreesImplementations#26]
used on #24 

> En un primer paso se determinan los dos rectángulos más distantes, siguiendo los pasos de LinearSplit #25 . Luego:
>  - Se defina la _dirección de corte_ como el eje perpendicular a la dimensión que tenía la mayor separación normalizada (resolver empates arbitrariamente)
> - Los _M+1_ rectángulos se ordenan por valor mínimo a lo largo del eje (ej. para el eje horizontal, se ordenan por la coordenada del lado izquierdo)
> - Los primeros _M/2-1_ rectángulos quedan en el primer nodo, mientras que los restantes quedan en el segundo

**Node**
 ```java
Long greeneSplit(){
  ArrayList<Rectangle> farTrees = this.farestResctangle();
  //inicia método greene para rellenar ambos hijos
}
```

A,B =  mas distantes como en Linear
d = direccion con separacion maxima de A,B 
sort(restantes, lambda x: x[d])
A.append(restantes[:-(M/2-1)])
B.append(restantes[-(M/2):])

**Comment by BastyZ** [comment]
relativo a esta función en especifico solo queda 
- [x] hacer una verificación de la coherencia del método, especialmente de la asignación de hijos/hermanos
- [x] determinar el método de sorting (yo voto heapsort bc yolo) igual según [esta página](https://www.toptal.com/developers/sorting-algorithms/random-initial-order) es uno de los más rápidos,  y según recuerdo es fácil de implementar.
- implementar las fx de horizontal and vertical sorting, que dejaré como issue aparte c:

Después de terminar los checkboxes yo daría por cerrado el issue @AnnBenavides
