### ISSUE TITLE
Constructor of Rectangle class

### ISSUE THREAD

**Issue by BastyZ** [BastyZ/RTreesImplementations#6]
Dado que hemos decidido que el rectángulo fuera una variable en particular con variables:
- int left
- int right
- int top
- int bottom

exclusivamente en ese orden, queda ponerse de acuerdo en como crecen espacialmente los objetos, ya que no es lo mismo que Y crezca hacia arriba o hacia abajo desde el concepto, ya que puede arruinar las comparaciones.

**Comment by AnnBenavides** [comment]
El eje X crece de izq a derecha y el eje Y de abajo hacia arriba :D
