### ISSUE TITLE
WTF should we do with files

### ISSUE THREAD

**Issue by BastyZ** [BastyZ/RTreesImplementations#7]
Averiguar como es el trato de estos objetos en memoria secundaria, quizas consultarlo en el __chat de logaritmos__ para saber si nuestro approach es el correcto.

**Comment by AnnBenavides** [comment]
Manejar la estructura como archivo:
-Nodo interno = carpeta
-Hoja = archivo

**Comment by BastyZ** [comment]
Vamos a usar java.io.Serializable como mencionamos en el issue #9 
Tutorial: https://www.tutorialspoint.com/java/java_serialization.htm

La idea es que cada nodo sea un archivo y la lista de hijos contenga la dirección relativa de cada uno. Hace falta implementar un manager para los nombres de archivo.

__no puedes tener un elemento de la misma clase dentro de un objeto__, se corre el riesgo de que quede guardado el árbol entero en el archivo.

**Comment by BastyZ** [comment]
this is a test
